version: "3"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
    ports:
      - "3000:8080"
  frontend:
    depends_on:
      - backend
    build:
      context: ./client
    environment:
      NODE_ENV: production

  backend:
    build:
      context: ./server
    environment:
      NODE_ENV: production
