version: "3"
services:
  web:
    depends_on:
      - backend
    build:
      context: ./client
      target: runner
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
