env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - node_modules
  - dist
rules:
  "@typescript-eslint/no-explicit-any": "off" # TODO: turn on eventually
  "@typescript-eslint/no-namespace": "off"
