name: Linting

on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Build client
        run: npm run build
        working-directory: ./client

      - name: Build server
        run: npm run build
        working-directory: ./server

      - name: Lint client code
        run: npx eslint .
        working-directory: ./client

      - name: Lint server code
        run: npx eslint .
        working-directory: ./server
