name: Linting

on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm run build
        working-directory: ./client
      - run: npm run build
        working-directory: ./server
      - run: npm eslint .
        working-directory: ./client
      - run: npm eslint .
        working-directory: ./server
