name: Test

on:
  push:
    branches:
      - main
      - 23-terraform # TODO: just for testing, remove later
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run test script
        run: sh run-tests.sh

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
